### ISSUE TITLE
Rendering a large file (200k+) takes too long - rangeSelect, pan, ...

### ISSUE THREAD

**Issue by breznak** [nupic-community/nupic.visualizations#16]
Working on real-life data, my files have something like 3M lines, even 280k lines file takes too long to open,zoom,pan, etc that it is not suitable for normal workflow. 

Can you replicate the problem, and if so, what can we do to overcome it? Optimizing the framework, or need to switch to some faster components? I was unable to debug which part is "freezing" the system, but assume it's the dygraph as the problem appeared when zooming a graph.

**Comment by jefffohl** [comment]
We could perhaps use a web worker to parse the data - so this part is working on a different thread than the main. Then, we could chunk the data as the web worker processes the data, so you don't have to sit there waiting for the entire data set to be parsed. Just thinking out loud here, I can do some tests later - don't have much time today.

**Comment by breznak** [comment]
My recent idea was to use `subsampling`:
- keep all the raw data in RAM
- set some internal constant POINTS_TO_SHOW=10.000
- subsample the data
- plot
  - if the user zooms, subsample again from raw

Maybe the framework could to that already?

**Comment by breznak** [comment]
@rhyolight in RiverView you may hit a similar problem, have you had to deal with it?

**Comment by rhyolight** [comment]
I limited the max # of rows to display in River View to 5000 I think.

---

Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by breznak** [comment]
We should try with the newest release, promises some speedup in `fillGraph` 
https://github.com/danvk/dygraphs/releases 
If it does not help, I'll contact upstream in https://github.com/danvk/dygraphs/issues/496

**Comment by breznak** [comment]
Updating the title to focus only on the problem of rendering - when rangeSelect, zoom at would take too much time.

**Comment by adamborowski** [comment]
@breznak I develop such framework:
see https://github.com/adamborowski/explorejs 
here is demonstration of integration with Dygrahps, please see https://youtu.be/b_VRyhak5Xg
It is not yet documented but there are many examples of many charts libraries integration
Cheers,
Adam
