### ISSUE TITLE
As a user, I want to be able to visualize data that doesn't have a timestamp

### ISSUE THREAD

**Issue by jefffohl** [nupic-community/nupic.visualizations#2]
Allow the user the option to use the iteration as the timestamp.

**Comment by breznak** [comment]
Some people at my uni showed interest in our project, but the `timestamp` hard requirement is a trouble. 
How to best approach this? 
- use radio-btn column (as for reference scale value) to select which column means "time"? 
- if no 'timestamp' found, assume implicit `1..N`
- have a text entry to change the value of `TIMESTAMP` variable
  ...?
