### ISSUE TITLE
As a user, I want the graph to highlight time in which a designated series passes a threshold, so I can easily see when anomalies occur.

### ISSUE THREAD

**Issue by jefffohl** [nupic-community/nupic.visualizations#3]
See this PR for some work in progress: https://github.com/breznak/nupic/pull/16

It would be good if the user could select a time series in the options UI, and then use a slider to set a threshold, based on the min-max of that particular series' data.

**Comment by breznak** [comment]
@jefffohl can you give me any tips for which framework to grab here? I'm trying to read up on "scientific JS" but I'm a bit lost. I want something like numpy in JS, for : 

```
anomalyIdx = numpy.where(loadedCSV[seriesId] > 0.9)
```

**Comment by jefffohl** [comment]
I don't know of a library with that exact function. I could write a version of one for you, if you like. Or, we could look around for a library that does what you are looking for. Here is a page I found that lists a number of math libraries: http://jster.net/category/math-libraries

**Comment by breznak** [comment]
Thank you Jeff. I'll try to find a numpy-like JS lib. I have a nice idea how to improve the threshold detection dynamically.

**Comment by rhyolight** [comment]
I have an example of highlighting in River View: http://data.numenta.org/chicago-beach-water-quality/Calumet%20Beach/data.html

![screen shot 2015-12-18 at 10 12 46 am](https://cloud.githubusercontent.com/assets/15566/11903688/e900bf32-a56f-11e5-97bb-3c215f7dbac3.png)

But this is conditional only on the X time value, not the actual Y value, which I have found to be particularly tricky. Anyway, here is the messy code that does this: https://github.com/nupic-community/river-view/blob/master/site/templates/scalar-data.html#L39-L85

**Comment by breznak** [comment]
Cool @rhyolight ! :sunglasses: this is the kickstart I need
