### ISSUE TITLE
As a user, I want some feedback after the "Render" button is clicked, so that on very large files, I know that the app is not broken.

### ISSUE THREAD

**Issue by jefffohl** [nupic-community/nupic.visualizations#32]

**Comment by breznak** [comment]
:+1: I already had that feeling. 
- one could use the existing functionality of "warning" labels to deliver that information? 
- another UX thing: after selecting `Browse` it already takes some time (PapaParse), then the new name appears in the text field. BUT one has to click the `Render` to redraw a graph (why?) It's esp. confusing whene there is already an older (and similar) graph drawn, one can forget to redraw with Render.
  - I'd like to suggest submitting the "render" function automatically when a file is selected in Browse.

**Comment by jefffohl** [comment]
@breznak - I don't think we need anything like a warning label - just something minimal, like an animation. You are right about the "Render" button being unnecessary - I think at one point there was thinking that you could load multiple files, and then choose which one to render  - but that is no longer something we want to do, so getting rid of it makes sense.

**Comment by breznak** [comment]
@ multiple files: this still sounds like a good idea (eg NAB, comparing results). But it has complications of the speed things. An idea would be to have some settings "duplicate 4x under each other", and then show 4 screens with the selection dialog and a graph.

**Comment by breznak** [comment]
@jefffohl can we close this?

**Comment by jefffohl** [comment]
@breznak - yes, closing this now. Though, we now need an animation for feedback on downloading remote files.
