### ISSUE TITLE
Hosting online version of the project - Easy deployment

### ISSUE THREAD

**Issue by breznak** [nupic-community/nupic.visualizations#35]
I'm trying to show this project to other people (medics, ...) and ease of running it is a problem. 
Some don't know/have a local server, so it's a blocker to give it a try! 
- maybe Numenta could host a page online for us
- I will try if the "Github pages" could do the work
- ???

**Comment by breznak** [comment]
Ok, I've followed https://pages.github.com/ with some success, looks it could be possible to "host" it there. See 
https://nupic-community.github.io/nupic.visualizations/

But I'm getting the error:

```
Refused to execute script from 'https://raw.githubusercontent.com/nupic-community/nupic.visualizations/master/build/external.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

Even though in `index.html` the type is set to `text/javascript`!? Any idea how to overcome that @jefffohl ?

**Comment by rhyolight** [comment]
I will deploy to Heroku today and add instructions on how to deploy.

**Comment by breznak** [comment]
@rhyolight you're awesome! :clap:
