### ISSUE TITLE
As a user, I want to see all the data info as I move my cursor over the graph

### ISSUE THREAD

**Issue by jefffohl** [nupic-community/nupic.visualizations#4]
Right now, the user must click on a point on the graph in order to see the exact timestamp value of a point on the graph. It would be useful to put the x-axis value in the field list to the right of the graph.

**Comment by breznak** [comment]
I got a new feed-back: show all the data (the row)(even the non-plotted one) under the cursor
- add a div "Current data"
- print (all) the row's content under the cursor

**Comment by jefffohl** [comment]
Closed via https://github.com/breznak/nupic.visualizations/pull/1
