### ISSUE TITLE
When loading a new data file with time after loading one w/o time, chart thinks there is no time

### ISSUE THREAD

**Issue by rhyolight** [nupic-community/nupic.visualizations#51]
[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/iwQh-vltuBY/0.jpg)](http://www.youtube.com/watch?v=iwQh-vltuBY)

**Comment by jefffohl** [comment]
Note that the error message doesn't display, but you can see that the x-axis does not get parsed as time, but instead as an iteration.

**Comment by breznak** [comment]
Thanks guys! I've prolly introduced that.
